TRG-1256: Update Ruby from 2.7.7 to 3.2
Doing this as `bundler` started failing our builds today since Ruby 2.7.7 is EOL:

>ERROR:  Error installing bundler:
 	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.7.221.

Upgrading to 3.2 required the explicit addition of the `rexml` gem. `rexml` was a default gem in 2.7.7 whereas it is a bundled gem in 3.2.

Also upgraded `vcr` to resolve this issue, which was observed running `rspec`:

>warning: Exception in finalizer #<Proc:0x00007f4b983f5bc0 /home/egrant/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vcr-6.0.0/lib/vcr/library_hooks/webmock.rb:36 (lambda)>
 /home/egrant/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vcr-6.0.0/lib/vcr/library_hooks/webmock.rb:36:in `block in global_hook_disabled_requests': wrong number of arguments (given 1, expected 0) (ArgumentError)

Co-authored-by: eddgrant <edd.grant@digital.hmrc.gov.uk>
Co-authored-by: Laurence de Bruxelles <laurence.debruxelles@dsit.gov.uk>